### ISSUE TITLE
All of the elements don't fit on my screen

### ISSUE THREAD

**Issue by mattfogel** [fuzzy-ai/lemonade-stand#4]
On my 13" MacBook Pro, I can't see all of the elements on the page on a single screen. Could you tighten up the UI so that it's a little more compact and fits on most screens?

<img width="1277" alt="hot_chocolate_stand" src="https://cloud.githubusercontent.com/assets/8151363/21854049/530a94de-d7e7-11e6-85a5-4d147fbb199e.png">

**Comment by pabloboerr** [comment]
closed via #a107aea
