### ISSUE TITLE
Update to intro text

### ISSUE THREAD

**Issue by mattfogel** [fuzzy-ai/lemonade-stand#5]
Here's new copy for the intro text

HOT CHOCOLATE STAND

The price of each cup of hot chocolate is decided by Fuzzy.ai. Try changing the number of people in line, the temperature or the weather and see how that affects the price. Check out the Profits chart below to see how well Fuzzy.ai learns to maximize profit.

**Comment by pabloboerr** [comment]
closed via #a107aea
