### ISSUE TITLE
Intro text after clicking Get Started

### ISSUE THREAD

**Issue by mattfogel** [fuzzy-ai/lemonade-stand#7]
After you click "Get Started", the intro text disappears and the screen scrolls down to show the hot chocolate stand. The thing is, you can still scroll back up and see empty space. Would it be difficult to keep the intro text there and just hide the Get Started button in case the user scrolls back up?

**Comment by pabloboerr** [comment]
No problem, I'll implement that right away.

**Comment by pabloboerr** [comment]
closed via #a107aea
